# Generated by Django 3.2.14 on 2022-08-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNegativePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointTitle', models.CharField(help_text='در این فیلد عنوان نکات منفی ذخیره میشود', max_length=20)),
                ('pointValue', models.FloatField(help_text='در این فیلد ارزش نکات منفی ذخیره میشود')),
                ('description', models.TextField(blank=True, help_text='در این فیلد توصیحات نکات منفی ذخیره میشود', null=True)),
            ],
            options={
                'verbose_name_plural': 'TechnicianNegativePoints',
            },
        ),
        migrations.CreateModel(
            name='CustomerPositivePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointTitle', models.CharField(help_text='در این فیلد عنوان نکات مثبت ذخیره میشود', max_length=20)),
                ('pointValue', models.FloatField(help_text='در این فیلد ارزش نکات مثبت ذخیره میشود')),
                ('description', models.TextField(blank=True, help_text='در این فیلد توصیحات نکات مثبت ذخیره میشود', null=True)),
            ],
            options={
                'verbose_name_plural': 'TechnicianPositivePoints',
            },
        ),
        migrations.CreateModel(
            name='TechnicianNegativePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointTitle', models.CharField(help_text='در این فیلد عنوان نکات منفی ذخیره میشود', max_length=20)),
                ('pointValue', models.FloatField(help_text='در این فیلد ارزش نکات منفی ذخیره میشود')),
                ('description', models.TextField(blank=True, help_text='در این فیلد توضیحات مربوط نکات منفی ذخیره میشود', null=True)),
            ],
            options={
                'verbose_name_plural': 'TechnicianNegativePoints',
            },
        ),
        migrations.CreateModel(
            name='TechnicianPositivePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointTitle', models.CharField(help_text='در این فیلد عنوان نکات مثبت ذخیره میشود', max_length=20)),
                ('pointValue', models.FloatField(help_text='در این فیلد ارزش نکات مثبت ذخیره میشود')),
                ('description', models.TextField(blank=True, help_text='در این فیلد توضیحات مربوط نکات مثبت ذخیره میشود', null=True)),
            ],
            options={
                'verbose_name_plural': 'TechnicianPositivePoints',
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorityName', models.CharField(help_text='در این فیلد نامی برای اولویت تیکیت ذخیره میشود', max_length=10)),
                ('priorityTitle', models.CharField(help_text='در این فیلد عنوان برای اولویت تیکیت ذخیره میشود', max_length=10)),
                ('description', models.TextField(blank=True, help_text='در این فیلد توضیحات برای اولویت تیکیت ذخیره میشود', null=True)),
            ],
            options={
                'verbose_name_plural': 'TicketStatus',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(help_text='در این فیلد نامی برای وضعیت تیکیت ذخیره میشود', max_length=10)),
                ('statusTitle', models.CharField(help_text='در این فیلد نامی عنوان وضعیت تیکیت ذخیره میشود', max_length=10)),
                ('description', models.TextField(blank=True, help_text='در این فیلد توصیحات برای وضعیت تیکیت ذخیره میشود', null=True)),
            ],
            options={
                'verbose_name_plural': 'TicketStatus',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNo', models.CharField(help_text='در این فیلد شماره تیکیت ذخیره میشود', max_length=10)),
                ('createDateTime', models.DateTimeField(help_text='در این فیلد زمان ثبت تیکیت ذخیره میشود')),
                ('closedDateTime', models.DateTimeField(blank=True, help_text='در این فیلد زمان بستن تیکیت ذخیره میشود', null=True)),
                ('answerBy', models.ForeignKey(help_text='در این فیلد پاسخ دهنده تیکیت ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, related_name='answerBy', to=settings.AUTH_USER_MODEL)),
                ('createBy', models.ForeignKey(help_text='در این فیلد ثبت کننده تیکیت ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, related_name='CreateBY', to=settings.AUTH_USER_MODEL)),
                ('ticketPriority', models.ForeignKey(help_text='در این فیلد اولویت تیکیت از جدول TicketPriority ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to='support.ticketpriority')),
                ('ticketStatus', models.ForeignKey(help_text='در این فیلد وضعیت تیکیت از جدول TicketStatus ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to='support.ticketstatus')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='در این فیلد متن تیکیت ذخیره میشود')),
                ('chatDateTime', models.DateTimeField(help_text='در این فیلد زمان ثبت تیکیت ذخیره میشود')),
                ('answerTo', models.ForeignKey(blank=True, help_text='در این فیلد مشخص می شود به کدام تیکیت پاسخ داده شده است', null=True, on_delete=django.db.models.deletion.CASCADE, to='support.ticketchats')),
                ('sender', models.ForeignKey(help_text='در این فیلد ارسال کننده تیکیت ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticketNo', models.ForeignKey(help_text='در این فیلد شماره تیکیت از جدول Tickets ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to='support.tickets')),
            ],
            options={
                'verbose_name_plural': 'TicketChats',
            },
        ),
        migrations.CreateModel(
            name='TechnicianSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderRating', models.FloatField(help_text='در این فیلد امتیاز سفارش ذخیره میشود')),
                ('survayDate', models.DateTimeField(help_text='در این فیلد عنوان زمان ثبت یازخورد ذخیره میشود')),
                ('orderId', models.ForeignKey(help_text='در این فیلد مشخص میشود این بازخورد مربوط به کدام سفارش است', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('technicianNegativePoints', models.ForeignKey(help_text='در این فیلد  نکات منفی تکنسین ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to='support.techniciannegativepoints')),
                ('technicianPositivePoints', models.ForeignKey(help_text='در این فیلد  نکات مثبت تکنسین ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to='support.technicianpositivepoints')),
                ('userID', models.ForeignKey(help_text='در این فیلد فرد ثبت کننده بازخورد ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TechnicianSurvey',
            },
        ),
        migrations.CreateModel(
            name='CustomerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderRating', models.FloatField(help_text='در این فیلد امتیاز سفارش ذخیره میشود')),
                ('surveyDate', models.DateTimeField(help_text='در این فیلد عنوان زمان ثبت یازخورد ذخیره میشود')),
                ('customerNegativePoints', models.ForeignKey(help_text='در این فیلد  نکات منفی مشتری ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to='support.customernegativepoints')),
                ('customerPositivePoints', models.ForeignKey(help_text='در این فیلد  نکات مثبت مشتری ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to='support.customerpositivepoints')),
                ('orderId', models.ForeignKey(help_text='در این فیلد مشخص میشود این بازخورد مربوط به کدام سفارش است', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('userID', models.ForeignKey(help_text='در این فیلد فرد ثبت کننده بازخورد ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CustomerSurvey',
            },
        ),
    ]
