# Generated by Django 3.2.14 on 2022-08-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNegativePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointTitle', models.CharField(max_length=20)),
                ('pointValue', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TechnicianNegativePoints',
            },
        ),
        migrations.CreateModel(
            name='CustomerPositivePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointTitle', models.CharField(max_length=20)),
                ('pointValue', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TechnicianPositivePoints',
            },
        ),
        migrations.CreateModel(
            name='TechnicianNegativePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointTitle', models.CharField(max_length=20)),
                ('pointValue', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TechnicianNegativePoints',
            },
        ),
        migrations.CreateModel(
            name='TechnicianPositivePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointTitle', models.CharField(max_length=20)),
                ('pointValue', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TechnicianPositivePoints',
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorityName', models.CharField(max_length=10)),
                ('priorityTitle', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TicketStatus',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=10)),
                ('statusTitle', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TicketStatus',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNo', models.CharField(max_length=10)),
                ('createDateTime', models.DateTimeField()),
                ('closedDateTime', models.DateTimeField(blank=True, null=True)),
                ('answerBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerBy', to=settings.AUTH_USER_MODEL)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreateBY', to=settings.AUTH_USER_MODEL)),
                ('ticketPriority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ticketpriority')),
                ('ticketStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ticketstatus')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('chatDateTime', models.DateTimeField()),
                ('answerTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.ticketchats')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticketno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.tickets')),
            ],
            options={
                'verbose_name_plural': 'TicketChats',
            },
        ),
        migrations.CreateModel(
            name='TechnicianSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderRating', models.FloatField()),
                ('survayDate', models.DateTimeField()),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('technicianNegativePoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.techniciannegativepoints')),
                ('technicianPositivePoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.technicianpositivepoints')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TechnicianSurvey',
            },
        ),
        migrations.CreateModel(
            name='CustomerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderRating', models.FloatField()),
                ('survayDate', models.DateTimeField()),
                ('customerNegativePoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.customernegativepoints')),
                ('customerPositivePoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.customerpositivepoints')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CustomerSurvey',
            },
        ),
    ]
