# Generated by Django 3.2.14 on 2022-08-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commissionRuleName', models.CharField(help_text='در این فیلد یک نام برای فرمول محاسبه پورسانت ذخیره می شود', max_length=20)),
                ('technicianCommission', models.FloatField(help_text='در این فیلد سهم تکنسین ذخیره می شود')),
                ('companyCommission', models.FloatField(help_text='در این فیلد شهم شرکت ذخیره می شود')),
                ('appliances', models.ForeignKey(help_text='در این فیلد نوع لوازم خانگی ذخیره می شود', on_delete=django.db.models.deletion.CASCADE, to='baseinfo.appliances')),
                ('customerCategory', models.ForeignKey(help_text='در این فیلد نوع مشتری ذخیره می شود', on_delete=django.db.models.deletion.CASCADE, to='baseinfo.customercategory')),
            ],
            options={
                'verbose_name_plural': 'CommissionRules',
            },
        ),
    ]
