# Generated by Django 3.2.14 on 2022-08-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
        ('order', '0002_initial'),
        ('accountant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commissionRuleName', models.CharField(max_length=20)),
                ('technicianCommission', models.FloatField()),
                ('companyCommission', models.FloatField()),
                ('appliances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.appliances')),
                ('customerCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.customercategory')),
                ('orderKind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.kindoforder')),
                ('paymentKind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.paymentkind')),
                ('technicianCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.techniciancategory')),
            ],
            options={
                'verbose_name_plural': 'CommissionRules',
            },
        ),
    ]
