# Generated by Django 3.2.14 on 2022-08-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='RegionsGeofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionLat', models.FloatField()),
                ('regionLong', models.FloatField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.provinces')),
            ],
            options={
                'verbose_name_plural': 'RegionsGeofence',
            },
        ),
        migrations.CreateModel(
            name='ProvinceGeofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceLat', models.FloatField()),
                ('provinceLong', models.FloatField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.provinces')),
            ],
            options={
                'verbose_name_plural': 'ProvinceGeofence',
            },
        ),
    ]
