# Generated by Django 3.2.14 on 2022-11-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliancessupplier',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='در این فیلد نام تامین کننده دستگاه مشخص میشود', null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.supplier'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='applianceBrand',
            field=models.ForeignKey(help_text='در این فیلد مشخص میشود که هریک از مدلهای به کدام برند مربوط است', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='baseinfo.appliancebrands'),
        ),
        migrations.AddField(
            model_name='appliancebrands',
            name='a_barndCategory',
            field=models.ForeignKey(help_text='در این فیلد مشخص میشود که هریک از برند های به کدام نوع از لوازم خانگی مربوط است', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='baseinfo.appliancecategories'),
        ),
        migrations.AddField(
            model_name='aplliancecategoryproblems',
            name='appliancescategory',
            field=models.ForeignKey(help_text='در این فیلد مشحص میشود مشکل مربوط به کدام یک از لوازم خانگی است', on_delete=django.db.models.deletion.CASCADE, related_name='appCatProblem', to='baseinfo.appliancecategories'),
        ),
        migrations.AddField(
            model_name='aplliancecategoryproblems',
            name='problemKind',
            field=models.ForeignKey(blank=True, help_text='در این فیلد نوع مشکل ذخیره می شود', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.problemskind'),
        ),
    ]
