# Generated by Django 3.2.14 on 2022-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'MembersPermission',
            },
        ),
    ]
