# Generated by Django 3.2.14 on 2022-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0003_memberspermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='baseinfo.MembersPermission'),
        ),
    ]
