# Generated by Django 3.2.14 on 2022-10-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_membersgroup_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberspermission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
