# Generated by Django 3.2.14 on 2022-09-28 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(help_text='نام بانک در این فیلد ذخیره میشود', max_length=20)),
                ('bankAccountNO', models.CharField(help_text='شماره حساب در این فیلد ذخیره میشود', max_length=20)),
                ('bankAccountSHABA', models.CharField(help_text='شماره شبا مربوط به حساب بانکی ذخیره می شود', max_length=20)),
                ('createDate', models.DateTimeField(help_text='در این فیلد مشخص میشود این حساب در تاریخی در سیستم ثبت شده است')),
            ],
            options={
                'verbose_name_plural': 'BankAccountInfo',
            },
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.BooleanField(help_text='در این فیلد هزینه انجام شده ذخیره می شود')),
                ('revenue', models.BooleanField(help_text='در این فیلد میزان سود ذخیره می شود')),
                ('technicianCommission', models.BooleanField(help_text='در این فیلد میزان پورسانت تکنسین ذخیره می شود')),
                ('companyCommission', models.BooleanField(help_text='در این فیلد میزان سهم شرکت ذخیره می شود')),
            ],
            options={
                'verbose_name_plural': 'Commissions',
            },
        ),
        migrations.CreateModel(
            name='InvoiceKinds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceKinds', models.CharField(help_text='عنوان نوع فاکتور', max_length=20)),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به نوع فاکتور', null=True)),
            ],
            options={
                'verbose_name_plural': 'InvoiceKinds',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNo', models.CharField(help_text='شماره فاکتور', max_length=20)),
                ('accepted', models.BooleanField(help_text='مشخص میکند آیا فاکتور توسط مشتری تایید شده یا خیر')),
                ('acceptedDateTime', models.DateTimeField(help_text='تاریخ و ساعت تایید فاکتور در این قیلد ذخیره می شود')),
                ('acceptedBy', models.ForeignKey(help_text='اطلاعات مربوط به کاربر تایید کننده فاکتور در این فیلد ذخیره می شود', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoiceKind', models.ForeignKey(help_text='توسط این فیلد نوع فاکتور از جدول InvoiceKinds انتخاب می شود', on_delete=django.db.models.deletion.CASCADE, to='accountant.invoicekinds')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceKinds', models.CharField(help_text='عنوان وضعیت فاکتور', max_length=20)),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به وضعیت فاکتور', null=True)),
            ],
            options={
                'verbose_name_plural': 'InvoiceKinds',
            },
        ),
        migrations.CreateModel(
            name='PaymentKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentKind', models.CharField(help_text='عنوان نوع روش پرداخت', max_length=10)),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به نوع روش پرداخت', null=True)),
            ],
            options={
                'verbose_name_plural': 'PaymentKind',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='عنوان وضغیت پرداخت', max_length=20)),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به وضعیت پرداخت', null=True)),
            ],
            options={
                'verbose_name_plural': 'PaymentStatus',
            },
        ),
        migrations.CreateModel(
            name='TransactionKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionKind', models.CharField(help_text='عنوان نوع تراکنش در این فیلد ذخیره می شود', max_length=20)),
                ('descriptions', models.TextField(help_text='توضیحات مربوط به نوع تراکنش در این فیلد ذخیره می شود')),
            ],
            options={
                'verbose_name_plural': 'TransactionKind',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletName', models.CharField(help_text='شماره یکتا کیف پول در این فیلد ذخیره می شود', max_length=20)),
                ('credit', models.BigIntegerField(default=0, help_text='اعتبار کیف پول در این فیلد ذخیره می شود')),
                ('bankAccount', models.ForeignKey(help_text='در این فیلد مشخص می شود که کیف پول به چه حساب بانکی متصل است', on_delete=django.db.models.deletion.CASCADE, to='accountant.bankaccountinfo')),
                ('userID', models.ForeignKey(help_text='این فیلد مشخص میکند که این کیف پول مربوط به کدام کاربر می باشد', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDateTime', models.DateTimeField(help_text='در این فیلد تاریخ و ساعت تراکنش ذخیره می شود')),
                ('transactionAmount', models.BigIntegerField(help_text='در این فیلد میزان مبلغ تراکنش ذخیره می شود')),
                ('transactionKind', models.CharField(choices=[('PAY', 'واریز'), ('WITHDRAW', 'برداشت'), ('INCOME_TRANSFER', 'انتقال از'), ('OUTCOME_TRANSFER', 'انتقال به')], help_text='در این فیلد نوع تراکنش ذخیره می شود', max_length=20)),
                ('destinationKind', models.CharField(choices=[('ORDER', 'مربوط به سفارش'), ('WALLET', 'انتقال به کیف پول')], help_text='در این فیلد مشخص میشود این تراکنش مربوط به پرداخت سفارش است یا خارج از سفارش پرداخت شده است', max_length=20)),
                ('destinationInvoice', models.ForeignKey(help_text='در این فیلد مشخص میشود این تراکنش مربوط به کدام فاکتور صادر شده است', on_delete=django.db.models.deletion.CASCADE, to='accountant.invoices')),
                ('destinationWallet', models.ForeignKey(help_text='در این فیلد مشخص میشود این تراکنش مربوط به انتقال مبلغ به کدام کیف پول است', on_delete=django.db.models.deletion.CASCADE, related_name='Destination', to='accountant.wallet')),
                ('originWallet', models.ForeignKey(help_text='در این فیلد میشود تراکنش مربوط به کدام کیف پول مرتبظ است', on_delete=django.db.models.deletion.CASCADE, related_name='Orgin', to='accountant.wallet')),
                ('payer', models.ForeignKey(blank=True, help_text='در این فیلد کاربر پرداخت  کننده ذخیره می شود', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WalletTransactions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentNo', models.CharField(help_text='شماره یکتای پرادخت در این فیلد ذخیره می شود', max_length=10)),
                ('invoiceAmount', models.BigIntegerField(help_text='مبلغ پرادخت در این فیلد ذخیره می شود')),
                ('transactionDate', models.DateTimeField(help_text='تاریخ پرادخت در این فیلد ذخیره می شود')),
                ('transactionStatus', models.CharField(choices=[('SUCCESSFUL', 'موفق'), ('FAILED', 'ناموفق')], help_text='وضعیت تراکنش در این فیلد ذخیره می شود', max_length=10)),
                ('trackingCode', models.CharField(help_text='در این فیلد گد رهگیری پرداخت ذخیره می شود', max_length=30)),
                ('createBy', models.ForeignKey(help_text='در این فیلد مشخص میشود که پرداخت توسط کدام کاربر انجام شده است', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(help_text='در این فیلد مشخص میشود که پرداخت به کدام فاکتور مربوط می شود', on_delete=django.db.models.deletion.CASCADE, to='accountant.invoices')),
                ('status', models.ForeignKey(help_text='در این فیلد مشخص میشود که چرداخت ار چه نوعی هست و یکی از اطلاعات جدول PaymentStatus را برمیگرداند', on_delete=django.db.models.deletion.CASCADE, to='accountant.paymentstatus')),
                ('transactionKind', models.ForeignKey(help_text='در این فیلد توع ترکنش از جدول TransactionKind دخیره میشود', on_delete=django.db.models.deletion.CASCADE, to='accountant.transactionkind')),
                ('wallet', models.ForeignKey(blank=True, help_text='در این فیلد مشخص میشود که این پرداخت مربوط به کدام کیف پول است', null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant.wallet')),
            ],
            options={
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoiceStatus',
            field=models.ForeignKey(help_text='توسط این فیلد وضعیت فاکتور از جدول InvoiceStatus انتخاب می شود', on_delete=django.db.models.deletion.CASCADE, to='accountant.invoicestatus'),
        ),
    ]
