# Generated by Django 3.2.14 on 2022-08-07 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=20)),
                ('bankAccountNO', models.CharField(max_length=20)),
                ('bankAccountSHABA', models.CharField(max_length=20)),
                ('createDate', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'BankAccountInfo',
            },
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.BooleanField()),
                ('revenue', models.BooleanField()),
                ('technicianCommission', models.BooleanField()),
                ('companyCommission', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Commissions',
            },
        ),
        migrations.CreateModel(
            name='InvoiceKinds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceKinds', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'InvoiceKinds',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNo', models.CharField(max_length=20)),
                ('accepted', models.BooleanField()),
                ('acceptedDateTime', models.DateTimeField()),
                ('acceptedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoiceKind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.invoicekinds')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='PaymentKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentKind', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'PaymentKind',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'PaymentStatus',
            },
        ),
        migrations.CreateModel(
            name='TransactionKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionKind', models.CharField(max_length=20)),
                ('descriptions', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TransactionKind',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletName', models.CharField(max_length=20)),
                ('credit', models.BigIntegerField()),
                ('bankAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.bankaccountinfo')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDateTime', models.DateTimeField()),
                ('transactionAmount', models.BigIntegerField()),
                ('transactionKind', models.CharField(choices=[('PAY', 'واریز'), ('WITHDRAW', 'برداشت'), ('INCOME_TRANSFER', 'انتقال از'), ('OUTCOME_TRANSFER', 'انتقال به')], max_length=20)),
                ('destinationKind', models.CharField(choices=[('ORDER', 'مربوط به سفارش'), ('WALLET', 'انتقال به کیف پول')], max_length=20)),
                ('destinationInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.invoices')),
                ('destinationWallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destination', to='accountant.wallet')),
                ('originWallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orgin', to='accountant.wallet')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WalletTransactions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentNo', models.CharField(max_length=10)),
                ('invoiceAmount', models.BigIntegerField()),
                ('transactionDate', models.DateTimeField()),
                ('transactionStatus', models.CharField(choices=[('SUCCESSFUL', 'موفق'), ('FAILED', 'ناموفق')], max_length=10)),
                ('trackingCode', models.CharField(max_length=30)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.invoices')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.paymentstatus')),
                ('transactionKind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.transactionkind')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant.wallet')),
            ],
            options={
                'verbose_name_plural': 'Payment',
            },
        ),
    ]
