# Generated by Django 3.2.14 on 2022-08-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseinfo', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=100)),
                ('nationalId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('0', 'زن'), ('1', 'مرد')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('createdAt', models.DateTimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='./UserPersonalImages')),
                ('ageRang', models.IntegerField(blank=True, null=True)),
                ('authuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=100)),
                ('supplierTel', models.CharField(max_length=100)),
                ('supplierFax', models.CharField(max_length=100)),
                ('supplierEmail', models.CharField(max_length=100)),
                ('supplierAddress', models.CharField(max_length=500)),
                ('supplierAgentFirstName', models.CharField(max_length=10)),
                ('supplierAgentLastName', models.CharField(max_length=50)),
                ('supplierAgentMobile', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=11)),
                ('isMain', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
            ],
            options={
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='PersonAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, null=True)),
                ('fillProfile', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
            ],
            options={
                'verbose_name_plural': 'PersonAuth',
            },
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.CharField(max_length=11)),
                ('isMain', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
            ],
            options={
                'verbose_name_plural': 'Mobiles',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresslat', models.FloatField()),
                ('addresslong', models.FloatField()),
                ('addressStreet', models.TextField()),
                ('addressLane', models.TextField()),
                ('addressNo', models.SmallIntegerField()),
                ('addressUnit', models.SmallIntegerField(blank=True, null=True)),
                ('addressFloor', models.SmallIntegerField()),
                ('isMain', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.provinces')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.regions')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal.person')),
                ('technicianRank', models.FloatField()),
                ('activate', models.BooleanField()),
                ('technicianCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.techniciancategory')),
                ('technicianDevices', models.ManyToManyField(to='baseinfo.Devices')),
                ('technicianSkills', models.ManyToManyField(to='baseinfo.TechnicianSkills')),
            ],
            options={
                'verbose_name_plural': 'Technician',
            },
            bases=('personal.person',),
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal.person')),
                ('customerCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.customercategory')),
                ('customerDevices', models.ManyToManyField(to='baseinfo.Devices')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
            bases=('personal.person',),
        ),
        migrations.CreateModel(
            name='CompanyMembers',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal.person')),
                ('hireDate', models.DateField()),
                ('quitDate', models.DateField()),
                ('membersGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.membersgroup')),
            ],
            options={
                'verbose_name_plural': 'CompanyMembers',
            },
            bases=('personal.person',),
        ),
    ]
