# Generated by Django 3.2.14 on 2022-08-03 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseinfo', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=100)),
                ('nationalId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('0', 'زن'), ('1', 'مرد')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('createdAt', models.DateTimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='./UserPersonalImages')),
                ('ageRang', models.IntegerField(blank=True, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Person',
            },
        ),
        migrations.CreateModel(
            name='sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=11)),
                ('vercode', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'sms',
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumebr', models.CharField(max_length=11)),
                ('isMain', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
            ],
            options={
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='PersonAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, null=True)),
                ('fillprofile', models.BooleanField(blank=True, null=True)),
                ('catrgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PersonAuth',
            },
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumebr', models.CharField(max_length=11)),
                ('isMain', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
            ],
            options={
                'verbose_name_plural': 'Mobiles',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresslat', models.FloatField()),
                ('addresslong', models.FloatField()),
                ('addressStreet', models.TextField()),
                ('addressLane', models.TextField()),
                ('addressNo', models.SmallIntegerField()),
                ('addressUnit', models.SmallIntegerField(blank=True, null=True)),
                ('addressFloor', models.SmallIntegerField()),
                ('isMain', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.provinces')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.regions')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
