# Generated by Django 3.2.14 on 2022-11-03 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
        ('auth', '0013_user_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='نام فرد در این فیلد ذخیره میشود', max_length=50)),
                ('lastName', models.CharField(help_text='نام خانوادگی فرد در این فیلد ذخیره میشود', max_length=100)),
                ('nationalId', models.CharField(blank=True, help_text='کد ملی فرد در این فیلد ذخیره میشود', max_length=10, null=True)),
                ('birthDate', models.DateField(blank=True, help_text='تاریخ تولد فرد در این فیلد ذخیره میشود', null=True)),
                ('gender', models.CharField(blank=True, choices=[('0', 'زن'), ('1', 'مرد')], help_text='جنسیت فرد در این فیلد ذخیره میشود', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, help_text='ادرس ایمیل فرد در این فیلد ذخیره میشود', max_length=254, null=True)),
                ('createdAt', models.DateTimeField(help_text='تاریخ ثبت نام فرد در این فیلد ذخیره میشود')),
                ('picture', models.ImageField(blank=True, help_text='تصویر پروفایل فرد در این فیلد ذخیره میشود', null=True, upload_to='userimage/UserPersonalImages')),
                ('ageRang', models.IntegerField(blank=True, help_text='بازه سنی فرد در این فیلد ذخیره میشود', null=True)),
                ('authuser', models.ForeignKey(help_text=' در این فیلد مشخص میشود این فرد به چه نام کاربری در سیستم ثبت شده است', on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(help_text='سخض ثبت نام کننده فرد در این فیلد ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(help_text='در این فیلد نام تامین کننده ذحیره می شود', max_length=100)),
                ('supplierTel', models.CharField(help_text='در این فیلد شماره تماس تامین کننده ذحیره می شود', max_length=100)),
                ('supplierFax', models.CharField(help_text='در این فیلد فکس تامین کننده ذحیره می شود', max_length=100)),
                ('supplierEmail', models.CharField(help_text='در این فیلد ایمیل تامین کننده ذحیره می شود', max_length=100)),
                ('supplierAddress', models.CharField(help_text='در این فیلد آدرس تامین کننده ذحیره می شود', max_length=500)),
                ('supplierAgentFirstName', models.CharField(help_text='در این فیلد نام رابط تامین کننده ذحیره می شود', max_length=10)),
                ('supplierAgentLastName', models.CharField(help_text='در این فیلد نام خانوادگی رابط تامین کننده ذحیره می شود', max_length=50)),
                ('supplierAgentMobile', models.CharField(help_text='در این فیلد موبایل رابط تامین کننده ذحیره می شود', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal.person')),
                ('technicianFavourite', models.TextField(blank=True, help_text=' در این فیلد لوازم خانگی تخصصی تکنسین از جدول Devices ذخیره میشود', null=True)),
                ('technicianRank', models.FloatField(blank=True, help_text=' در این فیلد گرید تکنسین ذخیره میشود', null=True)),
                ('activate', models.BooleanField(blank=True, help_text=' در این فیلد فعال بودن یا نبود تکنسین ذخیره میشود', null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'ثبت نام اولیه'), ('1', 'مصاحبه اولیه'), ('2', 'مصاحبه فنی'), ('3', 'استخدام'), ('4', 'پایان همکاری')], max_length=20, null=True)),
                ('hireForm', models.TextField(blank=True, help_text=' در این فیلد اطلاعات فرم استخدامی تکنسین به صورت Json ذخیره میشود', null=True)),
                ('technicianCategory', models.ForeignKey(blank=True, help_text=' در این فیلد نوع تکنسین از جدول TechnicianCategory ذخیره میشود', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.techniciancategory')),
            ],
            options={
                'verbose_name_plural': 'Technician',
            },
            bases=('personal.person',),
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(help_text=' در این فیلد شماره ثابت ذخیره میشود', max_length=11)),
                ('isMain', models.BooleanField(help_text=' در این فیلد مشخص میشود آیا این شماره ثابت شماره اصلی قرد است یا نه')),
                ('person', models.ForeignKey(help_text=' در این فیلد مشخص میشود شماره ثابت مربوط به چه فردیست', on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='personal.person')),
            ],
            options={
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='PersonAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, help_text=' در این فیلد مشخص میشود فرد فعال است یا نه', null=True)),
                ('fillProfile', models.BooleanField(blank=True, help_text=' در این فیلد مشخص میشود آیا پروفایل فرد تکمیل شده است یا نه', null=True)),
                ('category', models.ForeignKey(help_text=' در این فیلد مشخص میشود فرد مربوط به چه گروه کاربری است', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('person', models.ForeignKey(help_text=' در این فیلد مشخص میشود اطلاعات مربوط به چه فردیست', on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PersonAuth',
            },
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.CharField(help_text=' در این فیلد شماره موبایل ذخیره میشود', max_length=11)),
                ('isMain', models.BooleanField(help_text=' در این فیلد مشخص میشود آیا این شماره موبایل شماره موبایل اصلی قرد است یا نه')),
                ('person', models.ForeignKey(help_text=' در این فیلد مشخص میشود شماره موبایل مربوط به چه فردیست', on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='personal.person')),
            ],
            options={
                'verbose_name_plural': 'Mobiles',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLat', models.FloatField(blank=True, help_text='در این فیلد عرض جعرافیایی ذحیره می شود', null=True)),
                ('addressLong', models.FloatField(blank=True, help_text='در این فیلد طول جعرافیایی ذحیره می شود', null=True)),
                ('addressStreet', models.TextField(help_text='در این فیلد اسم خیابان ذحیره می شود')),
                ('addressSubStreet', models.TextField(blank=True, help_text='در این فیلد اسم خیابان ذحیره می شود', null=True)),
                ('addressLane', models.TextField(help_text='در این فیلد اسم کوچه ذحیره می شود')),
                ('addressBuilding', models.TextField(blank=True, help_text='در این فیلد اسم کوچه ذحیره می شود', null=True)),
                ('addressNo', models.CharField(help_text='در این فیلد پلاک ذحیره می شود', max_length=30)),
                ('addressUnit', models.CharField(blank=True, help_text='در این فیلد واحد ذحیره می شود', max_length=30, null=True)),
                ('addressFloor', models.CharField(help_text='در این فیلد طبقه ذحیره می شود', max_length=30)),
                ('isMain', models.BooleanField(help_text=' در این فیلد مشخص میشود آیا این آدرس اصلی قرد است یا نه')),
                ('city', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه شهرستانی است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.cities')),
                ('county', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه شهرستانی است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.counties')),
                ('neighbourhood', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه محله ای است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.neighbourhoods')),
                ('person', models.ForeignKey(help_text=' در این فیلد مشخص میشود آدرس مربوط به چه فردیست', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='personal.person')),
                ('province', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه استانی است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.provinces')),
                ('region', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه منطقه ای است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.regions')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='TechnicianSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', models.BooleanField()),
                ('fix', models.BooleanField()),
                ('skillDescription', models.TextField(blank=True, help_text='در این فیلد توضیحات مربوط به مهارتها ذخیره می شود', null=True)),
                ('technicianBrand', models.ManyToManyField(blank=True, help_text=' در این فیلد لوازم خانگی تخصصی تکنسین از جدول Devices ذخیره میشود', null=True, to='baseinfo.ApplianceBrands')),
                ('techneician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.technician')),
            ],
            options={
                'verbose_name_plural': 'TechnicianSkills',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal.person')),
                ('customerCategory', models.ForeignKey(blank=True, help_text=' در این فیلد نوع مشتری از جدول CustomerCategory ذخیره میشود', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.customercategory')),
                ('customerDevices', models.ManyToManyField(blank=True, help_text=' در این فیلد لوازم خانگی مشتری از جدول Devices ذخیره میشود', null=True, to='baseinfo.Appliances')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
            bases=('personal.person',),
        ),
        migrations.CreateModel(
            name='CompanyMembers',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal.person')),
                ('hireDate', models.DateField(blank=True, help_text=' در این فیلد تاریخ استخدام ذخیره میشود', null=True)),
                ('quitDate', models.DateField(blank=True, help_text=' در این فیلد تاریخ اتمام همکاری ذخیره میشود', null=True)),
                ('membersGroup', models.ForeignKey(help_text=' در این فیلد سطح دسترسی (نوع کاربری)  برای کارمند شرکت  از جدول MembersGroup ذخیره میشود', on_delete=django.db.models.deletion.CASCADE, to='baseinfo.membersgroup')),
            ],
            options={
                'verbose_name_plural': 'CompanyMembers',
            },
            bases=('personal.person',),
        ),
    ]
