# Generated by Django 3.2.14 on 2022-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembers',
            name='hireDate',
            field=models.DateField(blank=True, help_text=' در این فیلد تاریخ استخدام ذخیره میشود', null=True),
        ),
        migrations.AlterField(
            model_name='companymembers',
            name='quitDate',
            field=models.DateField(blank=True, help_text=' در این فیلد تاریخ اتمام همکاری ذخیره میشود', null=True),
        ),
    ]
