# Generated by Django 3.2.14 on 2022-12-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_appliancescategorychecklist_brandschecklist_modelschecklist'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianskills',
            name='technicianBrand',
        ),
        migrations.AddField(
            model_name='technicianskills',
            name='technicianBrand',
            field=models.ForeignKey(blank=True, help_text=' در این فیلد لوازم خانگی تخصصی تکنسین از جدول Devices ذخیره میشود', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.appliancebrands'),
        ),
    ]
