# Generated by Django 3.2.14 on 2022-12-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_appliancescategorychecklist_brandschecklist_modelschecklist'),
        ('personal', '0002_auto_20221202_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianDistricts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه شهرستانی است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.cities')),
                ('county', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه شهرستانی است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.counties')),
                ('neighbourhood', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه محله ای است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.neighbourhoods')),
                ('province', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه استانی است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.provinces')),
                ('region', models.ForeignKey(blank=True, help_text=' در این فیلد مشخص آدرس مربوط به چه منطقه ای است', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.regions')),
                ('techneician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.technician')),
            ],
            options={
                'verbose_name_plural': 'TechnicianRegion',
            },
        ),
    ]
