# Generated by Django 3.2.14 on 2022-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20221215_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, help_text='تصویر پروفایل فرد در این فیلد ذخیره میشود', null=True, upload_to='usersimage/UserPersonalImages'),
        ),
    ]
