from django.contrib import admin
from baseinfo.models import *
admin.site.register(AppliancesSupplier)
admin.site.register(Problems)
admin.site.register(ApllianceCategoryProblems)
admin.site.register(BarndsProblems)
admin.site.register(Cities)
admin.site.register(Counties)
admin.site.register(CityGeofence)
admin.site.register(Neighbourhoods)
admin.site.register(NeighbourhoodGeofence)
admin.site.register(MembersGroup)
admin.site.register(MembersPermission)
admin.site.register(ApplianceCategories)
admin.site.register(ApplianceBrands)
admin.site.register(Appliances)
admin.site.register(DevicesPrice)
admin.site.register(Regions)
admin.site.register(ProvinceGeofence)
admin.site.register(Provinces)
admin.site.register(RegionsGeofence)
admin.site.register(CustomerCategory)
admin.site.register(TechnicianCategory)

admin.site.register(DevicesGuarantee)
admin.site.register(DevicesGuaranteeImages)
admin.site.register(Devices)
admin.site.register(HireForm)
admin.site.register(HireJson)
admin.site.register(OTPsms)
admin.site.register(Sms)
admin.site.register(SmsTypes)
admin.site.register(ProblemsKind)

admin.site.register(AppliancesCategoryCheckList)
admin.site.register(BrandsChecklist)
admin.site.register(ModelsChecklist)