from django.contrib import admin
from baseinfo.models import (
    Regions,
    ProvinceGeofence,
    Provinces,
    RegionsGeofence,
    CustomerCategory,
    TechnicianCategory,
    TechnicianSkills,
    DeviceCategories,
    DeviceBrands,
    Devices,
    HireJson,
    HireForm,
    OTPsms,
    Sms,
    SmsTypes,
    MembersGroup,
    ApplianceCategories,
    ApplianceBrands,
    AppliancesSupplier,
    Appliances,
    DevicesPrice,
    Problems,
    Cities,
    CityGeofence,
    Neighbourhoods,
    NeighbourhoodGeofence

)
admin.site.register(AppliancesSupplier)
admin.site.register(Problems)
admin.site.register(Cities)
admin.site.register(CityGeofence)
admin.site.register(Neighbourhoods)
admin.site.register(NeighbourhoodGeofence)
admin.site.register(MembersGroup)
admin.site.register(ApplianceCategories)
admin.site.register(ApplianceBrands)
admin.site.register(Appliances)
admin.site.register(DevicesPrice)
admin.site.register(Regions)
admin.site.register(ProvinceGeofence)
admin.site.register(Provinces)
admin.site.register(RegionsGeofence)
admin.site.register(CustomerCategory)
admin.site.register(TechnicianCategory)
admin.site.register(TechnicianSkills)
admin.site.register(DeviceCategories)
admin.site.register(DeviceBrands)
admin.site.register(Devices)
admin.site.register(HireForm)
admin.site.register(HireJson)
admin.site.register(OTPsms)
admin.site.register(Sms)
admin.site.register(SmsTypes)
