
from .views import *
from django.urls import path

urlpatterns = [
    path('CreateDesignJson/', CreateDesignJson.as_view()),
    path('GetAllDesignJson/', GetAllDesignJson.as_view()),
    path('getregions/', GetRegins.as_view()),
    path('getnabours/', getNabours.as_view()),
    path('getapplience/', getApplience.as_view()),
    path('getproblems/', getProblems.as_view()),
    path('createprovince/', CreateProvince.as_view()),
    path('createcounty/', CreateCounty.as_view()),
    path('createcity/', CreateCity.as_view()),
    path('createregion/', CreateRegion.as_view()),
    path('createneighbourhood/', CreateNeighbourhood.as_view()),
    path('editprovince/', EditProvince.as_view()),
    path('editcounty/', EditCounty.as_view()),
    path('editcity/', EditCity.as_view()),
    path('editregion/', EditRegion.as_view()),
    path('editneighbourhood/', EditNeighbourhood.as_view()),
    path('deleteprovince/', DeleteProvince.as_view()),
    path('deletecounty/', DeleteCounty.as_view()),
    path('deletecity/', DeleteCity.as_view()),
    path('deleteregion/', DeleteRegion.as_view()),

    path('createappliance/', CreateAppliance.as_view()),
    path('createbrand/', CreateBrand.as_view()),
    path('createmodel/', CreateModel.as_view()),
    path('editappliance/', EditAppliance.as_view()),
    path('editbrand/', EditBrand.as_view()),
    path('editmodel/', EditModel.as_view()),
    path('deleteappliance/', DeleteAppliance.as_view()),
    path('deletebrand/', DeleteBrand.as_view()),
    path('deletemodel/', DeleteModel.as_view()),
    path('createappliancecategoryproblem/', CreateApplianceCategoryProblem.as_view()),
    path('editappliancecategoryproblem/', EditApplianceCategoryProblem.as_view()),
    path('deleteappliancecategoryproblem/', DeleteApplianceCategoryProblem.as_view()),
    path('createappliancecategorychecklist/', CreateApplianceCategoryChecklist.as_view()),
    path('editappliancecategorychecklist/', EditApplianceCategoryChecklist.as_view()),
    path('deleteappliancecategorychecklist/', DeleteApplianceCategoryChecklist.as_view()),
    path('createbrandproblem/', CreateBrandProblem.as_view()),
    path('editbrandproblem/', EditBrandProblem.as_view()),
    path('deletebrandproblem/', DeleteBrandProblem.as_view()),
    path('createFCMdevice/', CreateFCMDevice.as_view()),
    path('sendFCM/', SendFCM.as_view()),
    path('getproblemkind/', GetProblemKind.as_view()),
    path('setlog/',SetLog.as_view()),

]