# Generated by Django 3.2.14 on 2022-09-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProblemPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemImage', models.ImageField(upload_to='images/CustomerProblems/')),
            ],
            options={
                'verbose_name_plural': 'CustomerProblemPic',
            },
        ),
        migrations.CreateModel(
            name='CustomerProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerDescription', models.TextField(blank=True, help_text='دراین فیلد توضیحات مربوط به مشکلات اظهاری مشتری ذخیره میشود', null=True)),
            ],
            options={
                'verbose_name_plural': 'CustomerProblems',
            },
        ),
        migrations.CreateModel(
            name='KindOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderKind', models.CharField(help_text='در این فیلد یک عنوان برای توع سفارش ذخیره می شود', max_length=20)),
                ('description', models.TextField(blank=True, help_text='در این فیلد توصیحات مربوط به نوع سفارش ذخیره می شود', null=True)),
            ],
            options={
                'verbose_name_plural': 'KindOfOrder',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerDateTime', models.DateTimeField(help_text='در این فیلد زمان ثبت سفارش ذخیره می شود')),
                ('orderDate', models.DateField(help_text='در این فیلد تاریخ انجام سفارش ذخیره می شود')),
                ('description', models.TextField(blank=True, help_text='در این فیلد توضیحات مازاد مربوط به انجام سفارش ذخیره می شود', null=True)),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='در این فیلد عنوان وضعیت ذخیره می شود', max_length=20)),
                ('description', models.TextField(blank=True, help_text='در این فیلد توضیحات مربوط به وضعیت ذخیره می شود', null=True)),
            ],
            options={
                'verbose_name_plural': 'OrderStatus',
            },
        ),
        migrations.CreateModel(
            name='OrderTimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeRange', models.CharField(help_text='در این فیلد یک نام برای بازه زمانی ذخیره می شود', max_length=20)),
                ('startTime', models.TimeField(help_text='در این فیلد ساعت شروع بازه زمانی ذخیره می شود')),
                ('endTime', models.TimeField(help_text='در این فیلد ساعت پایان بازه زمانی ذخیره می شود')),
                ('description', models.TextField(blank=True, help_text='در این فیلد توضیحات لازم برای بازه زمانی ذخیره می شود', null=True)),
            ],
            options={
                'verbose_name_plural': 'OrderTimeRange',
            },
        ),
        migrations.CreateModel(
            name='TechnicianProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicianDescription', models.TextField(blank=True, help_text='دراین فیلد توضیحات مربوط به مشکلات اظهاری تکنسین ذخیره میشود', null=True)),
                ('order', models.ForeignKey(help_text='در این فیلد مشخص میشود قطعه خریداری شده مربوط به کدام سفارش است', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('problem', models.ForeignKey(help_text='در این فلد مشکل از جدول Problems انتخاب میشود', on_delete=django.db.models.deletion.CASCADE, to='baseinfo.problems')),
            ],
            options={
                'verbose_name_plural': 'TechnicianProblems',
            },
        ),
        migrations.CreateModel(
            name='TechnicianProblemPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemImage', models.ImageField(upload_to='images/CustomerProblems/')),
                ('order', models.ForeignKey(help_text='در این فیلد مشخص میشود تصویر اپدیت شده مربوط به کدام سفارش است', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name_plural': 'CustomerProblemPic',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(help_text='در این فیلد مشخص میشود قطعه خریداری شده مربوط به کدام سفارش است', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name_plural': 'OrderDetails',
            },
        ),
    ]
