# Generated by Django 3.2.14 on 2022-08-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('personal', '0001_initial'),
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='soldIndividualDevice',
            field=models.ManyToManyField(to='warehouse.SoldIndividualDevice'),
        ),
        migrations.AddField(
            model_name='order',
            name='appliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.appliances'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.customers'),
        ),
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.devices'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.addresses'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderKind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.kindoforder'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderTimeRange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordertimerange'),
        ),
        migrations.AddField(
            model_name='order',
            name='registerBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.technician'),
        ),
    ]
