# Generated by Django 3.2.14 on 2022-12-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_hasguarantee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicianproblempic',
            options={'verbose_name_plural': 'TechnicianProblemPic'},
        ),
        migrations.AlterField(
            model_name='customerproblempic',
            name='problemImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/CustomerProblems/'),
        ),
        migrations.AlterField(
            model_name='technicianproblempic',
            name='problemImage',
            field=models.ImageField(upload_to='images/TechnicianProblems/'),
        ),
    ]
